### ISSUE TITLE
MPS : name constraints & variables

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#1051]
### Variables
1. Name
2. Location (if applicable)
3. Time identifier (week/day/hour)

Examples
```
Flow::link<id>::hour<h>
UnsupEnrg::area<id>::hour<h>
DispatchableProduction::area<area-id>::ThermalCluster<id>::hour<h>

```
### Constraints
Same idea as with variables

Examples
```
balance::area<id>::hour<h>
flowDissociation::link<id>::hour<h>
my-bc::weekly_bc::week<w>
HydroEnergySmoothingUsingVariationMaxUp::area<id>::hour<h>
HydroFinalLevelSumOfWaterValueSlices::area<id>::weekly
```

### TODO
- [ ] Handle variables and constraints that have not been named
- [ ] Remove unused file variable.txt
- [ ] Harmonize naming for variables and constraints
- [ ] Hamonize the code for variables and constraints
- [ ] Remove spaces & special characters in variable/constraint names
- [ ] ~~Handle empty constraint/variable names : "C%07d" or "R%07d" as before~~
- [ ] Name thermal clusters in **SIM_**

It may be necessary to convert `std::vector<std::string>` to `const char**`. Possible implementation
```cpp
#include <iostream>
#include <vector>
#include <string>

class Converter {
public:
  std::pair<const char**, size_t> run(const std::vector<std::string>& v)
  {
    p.resize(v.size());
    for (size_t idx = 0; idx < v.size(); ++idx) {
        p[idx] = v[idx].c_str();
    }
    return {p.data(), p.size()};
  }
private:
  std::vector<const char*> p;
};

int main() {
  std::vector<std::string> H = {"Hello", "world", " !"};
  Converter converter;
  auto [array, size] = converter.run(H);
  for (size_t idx = 0; idx < size; idx++)
  {
    std::cout << array[idx] << std::endl;
  }
}
```
