### ISSUE TITLE
Use singleton for timer

### ISSUE THREAD

**Issue by flomnes** [AntaresSimulatorTeam/Antares_Simulator#2014]
# TODO
- [ ] Remove class `NullDurationCollector`
- [ ] Remove `pDurationCollector` members, `duration_collector` arguments
- [ ] Initialize singleton (See logs.h / logs.cpp, use `extern` keyword in header file)
- [ ] Change syntax whenever required (see below)

# Current
```cpp
void f(Benchmarking::IDurationCollector& durationCollector)
{
    Benchmarking::Timer timer_wait;
    std::lock_guard guard(pZipMutex); // Wait
    timer_wait.stop();
    durationCollector.addDuration("zip_wait", timer_wait.get_duration());
}
```
# Proposed
```cpp
#include <duration-collector.hpp>

int main() {
  DurationCollector collector;
// Sweet sweet syntactic sugar
  collector("hello") << [] {
    using namespace std::chrono_literals;
    std::this_thread::sleep_for(200ms);
  };
// Lambdas can capture stuff, too
  int a;
  collector("world") << [&a] {
    a++;
  };
  collector.summary();
}
/* Possible output
hello	200
world	0
*/
```
## Possible implementation
 ```cpp
#include <functional>
#include <thread>
#include <chrono>
#include <iostream>
#include <map>

class DurationCollector {
public:
  using clock = std::chrono::steady_clock;

  std::map<std::string, long> times;

  struct OperationTimer {
    OperationTimer(DurationCollector& collector,
		   const std::string& key): key(key), collector(collector) {}
    
    DurationCollector& collector;
    const std::string key;
  };

  OperationTimer operator()(const std::string& key) {
    return OperationTimer(*this, key);
  }

  friend void operator<<(const OperationTimer& op, std::function<void(void)> f) {
    auto start_ = clock::now();
    f();
    auto end_ = clock::now();
    auto duration_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end_ - start_).count();
    op.collector.times[op.key] += duration_ms;
  }
  void summary() {
    for (auto& [k, v] : times)
      std::cout << k << '\t' << v << '\n';
  }
};
```
